### ISSUE TITLE
Font/Heading size updates below:

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/Gage-Communications-2017#11]
H1 - 44px
H2 - 36 px

There are so many font inconsistencies on this website. Some H1's are 48px, some are 44px. The team's names are a H2 and 52 px which is so silly. We've been wanting to downsize on fonts for awhile so let's try this out and make the headings consistent :)

**Comment by ccmorris** [comment]
The font sizes in the design were all over the place. I removed as many of the customized H2 font sizes from the code as I could.
