### ISSUE TITLE
About - Our Mission - Please allow for points 3 and 4 to fall on the second row to make it even

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/Gage-Communications-2017#9]

**Comment by ccmorris** [comment]
@tgascoigne14 I don't understand. Can you make a screenshot or something to demonstrate?

**Comment by ccmorris** [comment]
Oh the mission section was hidden. No wonder I was confused. Nvm!

**Comment by tgascoigne14** [comment]
Cool. Did you see all of the awesome content updates that the website has?
